artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: cppe-5
  local_data_file: artifacts/data_ingestion/data



data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/data
  STATUS_FILE: artifacts/data_validation/status.txt
  EXAMPLE_FILE: artifacts/data_validation/EXAMPLE_FILE.yaml



data_transformation:
  root_dir: artifacts/data_transformation
  transformed_data_path: artifacts/data_transformation/transformed_data
  checkpoint_path: artifacts/model_trainer/detr-resnet-50_finetuned_cppe5
  data_path: artifacts/data_ingestion/data



model_trainer:
  root_dir: artifacts/model_trainer
  checkpoint_path: artifacts/model_trainer/detr-resnet-50_finetuned_cppe5
  data_path: artifacts/data_ingestion/data



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  checkpoint_path: artifacts/model_trainer/detr-resnet-50_finetuned_cppe5
  model_path: artifacts/model_trainer
  metric_file_name: artifacts/model_evaluation/metrics.json